import {
  INCREMENT,
  DECREMENT,
  ADD_PATICIPANTS,
  CHANGE_ATTENDEE_DETAILS_SUCCESS,
  CHANGE_ATTENDEE_DETAILS_FAILED,
  LOADING,
  INCREMENT_DETAILS,
  DECREMENT_DETAILS,
  TICKET_DETAILS,
  TICKET_INCREMENT_DETAILS,
} from "./actionTypes";
